services:
  api:
    container_name: support-api-test
    env_file:
      - ./backend/.env.test
    volumes:
      - ./backend/pytest.ini:/backend/pytest.ini
    
  postgres:
    container_name: support-postgres-test
    environment:
      POSTGRES_DB: ${db_name_test}
      POSTGRES_USER: ${db_user_test}
      POSTGRES_PASSWORD: ${db_password_test}
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    ports:
      - "${db_port_test}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${db_user_test} -d ${db_name_test}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
  
  redis:
    container_name: support-redis-test
    volumes:
      - redis_data_test:/data


volumes:
  pgdata_test:
  redis_data_test: