# rules file for Ruff
target-version = "py314"
line-length = 92

[lint]
extend-select = [
    "UP", # pyupgrade
    "I", # isort
    "E501", # line too long
]
ignore = [
    "F401", # unused import
]

[format]
quote-style = "double"
indent-style = "tab"