"""add ticket model

Revision ID: 0c59398facda
Revises: b96a66d154fd
Create Date: 2026-03-18 23:12:27.351666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0c59398facda'
down_revision: Union[str, Sequence[str], None] = 'b96a66d154fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ticketstatus_enum = postgresql.ENUM(
    'NEW', 'OPEN', 'PENDING', 'IN_PROGRESS', 'RESOLVED', 'CLOSED',
    name='ticketstatus',
    create_type=False,
)

ticketpriority_enum = postgresql.ENUM(
    'LOW', 'MEDIUM', 'HIGH', 'CRITICAL',
    name='ticketpriority',
    create_type=False,
)

ticketcategory_enum = postgresql.ENUM(
    'TECHNICAL', 'GENERAL',
    name='ticketcategory',
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    ticketcategory_enum.create(bind, checkfirst=True)
    ticketpriority_enum.create(bind, checkfirst=True)
    ticketstatus_enum.create(bind, checkfirst=True)

    op.create_table('tickets',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', ticketstatus_enum, nullable=False, server_default="NEW"),
    sa.Column('priority', ticketpriority_enum, nullable=False, server_default="MEDIUM"),
    sa.Column('category', ticketcategory_enum, nullable=False, server_default="GENERAL"),
    sa.Column('customer_id', sa.BIGINT(), nullable=False),
    sa.Column('assigned_to_id', sa.BIGINT(), nullable=True),
    sa.Column('first_response_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolve_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assigned_to_id'), 'tickets', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_tickets_customer_id'), 'tickets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_uuid'), 'tickets', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_index(op.f('ix_tickets_uuid'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_customer_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_to_id'), table_name='tickets')
    op.drop_table('tickets')
    ticketcategory_enum.drop(bind, checkfirst=True)
    ticketpriority_enum.drop(bind, checkfirst=True)
    ticketstatus_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
