"""add user roles enum

Revision ID: b96a66d154fd
Revises: 39fabbc2a17c
Create Date: 2026-03-18 19:44:53.736469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b96a66d154fd'
down_revision: Union[str, Sequence[str], None] = '39fabbc2a17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = postgresql.ENUM(
    "CUSTOMER",
    "SUPPORT_AGENT",
    "ADMIN",
    name="role_enum",
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    role_enum.create(bind, checkfirst=True)
    op.add_column(
        "users",
        sa.Column(
            "role",
            role_enum,
            nullable=False,
            server_default="CUSTOMER",
        ),
    )

    op.alter_column(
        "user_sessions",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    )

    op.alter_column(
        "user_sessions",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_column("users", "role")
    role_enum.drop(bind, checkfirst=True)

    op.alter_column(
        "user_sessions",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
        server_default=None,
    )

    op.alter_column(
        "user_sessions",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
        server_default=None,
    )
    # ### end Alembic commands ###
